TILE_WIDTH = 20
TILE_COLOR = (150, 150, 150)
TILE_SPACING = 3

WINDOW_RATIO = 1
NUMBER_OF_TILES_HEIGHT = 40
NUMBER_OF_TILES_WIDTH = NUMBER_OF_TILES_HEIGHT * WINDOW_RATIO
WINDOW_HEIGHT = (
    NUMBER_OF_TILES_HEIGHT * TILE_WIDTH + (NUMBER_OF_TILES_HEIGHT - 1) * TILE_SPACING
)

WINDOW_WIDTH = (
    NUMBER_OF_TILES_HEIGHT * WINDOW_RATIO * TILE_WIDTH
    + (WINDOW_RATIO * NUMBER_OF_TILES_HEIGHT - 1) * TILE_SPACING
)

BOMB_COUNT = NUMBER_OF_TILES_HEIGHT * NUMBER_OF_TILES_WIDTH // 8
BOMB_COLOR = (255, 0, 0)
BOMB_WIDTH = TILE_WIDTH - TILE_WIDTH * 0.8
